### ISSUE TITLE
Mistake in ft_save_spy causes an error

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/syncopy-matlab#4]
This seems to be a simple oversight on this line:

https://github.com/esi-neuroscience/syncopy-matlab/blob/5d36d8acdd6d2058fb8379495c4d9efcb4010d4b/%2Bspy/ft_save_spy.m#L63

Replacing `6` by `end` solved my problem.

Original error message:
```
Unable to perform assignment because the size of the left side is 707-by-3 and the size of the right side is
707-by-6.

Error in spy.ft_save_spy (line 63)
    trl(:, 4:6) = datain.trialinfo;

Error in untitled (line 9)
spy.ft_save_spy(cfg, data)
```

**Comment by pantaray** [comment]
Good call - has been fixed. Thanks!
